// Generated by CoffeeScript 2.0.2
var Mode, defaultMode, normalize;

Mode = require('stat-mode');

defaultMode = 0o777 & ~process.umask();

normalize = function(mode) {
  var called, newMode;
  called = false;
  newMode = {
    owner: {},
    group: {},
    others: {}
  };
  ['read', 'write', 'execute'].forEach(function(key) {
    if (typeof mode[key] === 'boolean') {
      newMode.owner[key] = mode[key];
      newMode.group[key] = mode[key];
      newMode.others[key] = mode[key];
      called = true;
    }
  });
  if (called) {
    return newMode;
  } else {
    return mode;
  }
};

console.log(new Mode(0o777));

// console.log normalize { }
