// Generated by CoffeeScript 2.1.1
uses('punker-uglify');

tasks({
  js: [
    {
      needs: 'min'
    }
  ],
  min: [
    {
      entry: 'Punkfile.js'
    },
    min,
    {
      outFile: '2.js'
    }
  ]
});
