// Generated by CoffeeScript 2.1.1
module.exports = function(punk) {
  return punk.inputs = punk.i = punk.input = {
    buffer: function(f) {
      return async function(files) {
        await punk.d.eachAsync(files, function(file) {
          return file.contents = Buffer.from(file.contents);
        });
        return f(...arguments);
      };
    },
    string: function(f) {
      return async function(files) {
        await punk.d.eachAsync(files, function(file) {
          return file.contents = file.contents.toString();
        });
        return f(...arguments);
      };
    }
  };
};
