// Generated by CoffeeScript 2.0.2
//##################
// CONNECT MODULES #
//##################
var config, cwd, fs, path, process, punk, reporter, util;

process = require('process');

path = require('path');

fs = require('fs');

util = require('util');

// ###################
// DEFINE VARIABLES #
//###################
cwd = process.cwd();

config = process.mainModule.filename;

punk = {
  filename: config,
  dirname: path.dirname(config),
  reporter: reporter,
  plugins: {},
  converters: {},
  minifiers: {},
  // TODO: proxy config changes for merge changes with defaults
  _config: {
    changedDelay: 60 //ms
  }
};


// LOAD SEPARATED SCRIPTS
Object.assign(punk, require('./reporter.js')(punk));

reporter = punk.reporter;

Object.assign(punk, require('./dev.js')(punk, reporter));

Object.assign(punk, require('./run-task.js')(punk, reporter));

Object.assign(punk, require('./run.js')(punk, reporter));

Object.assign(punk, require('./use.js')(punk, reporter));

Object.assign(punk, require('./file.js')(punk, reporter));

punk.p = punk.plugins;

punk.d = punk.dev;

module.exports = punk;

Object.defineProperty(punk, 'config', {
  get: function() {
    return new Proxy(punk._config, {
      set: function(obj, prop, value) {
        return punk.d.merge(obj[prop], value);
      }
    });
  },
  set: function(c) {
    return punk.d.merge(punk._config, c);
  }
});

punk.config.a = {
  b: {
    c: 500
  }
};

reporter.message(punk.config);

//####################
// ADD BASIC PLUGINS #
//####################
punk.use([require('./plugins/bundle.js'), require('./plugins/mute.js'), require('./plugins/converter.js'), require('./plugins/minifier.js'), require('./plugins/concat.js'), require('./plugins/add.js'), require('./plugins/write.js')]);
