// Generated by CoffeeScript 2.0.2
var chokidar, pn;

chokidar = require('chokidar');

pn = require('pn/fs');

module.exports = function(punk, reporter) {
  var r;
  return r = {
    _runTask: async function(taskName, task) {
      var devnull, files, pipe, ref;
      reporter.startingTask(taskName);
      // set settings to standard format
      task = punk.d.toSetting(task);
      // load files
      files = (await punk.p.add(task.entry)({}, task));
      ref = task.pipes;
      // pass files through pipes
      for (devnull in ref) {
        pipe = ref[devnull];
        files = (await pipe(files, task));
      }
      // convert files
      if (task.to) {
        files = (await punk.p.to(task.to)(files, task));
      }
      // write files to FS
      files = (await punk.p.write(task)(files, task));
      // report
      reporter.finishedTask(taskName);
    },
    _watchTask: async function(taskName, task) {
      var changed;
      r._runTask(taskName, task);
      // set settings to standard format
      task = punk.d.toSetting(task);
      // load files
      chokidar.watch(task.entry).on('change', function(path) {
        return setTimeout(function() {
          return changed(punk.p.add(path)({}, task), path);
        }, punk.config.changedDelay);
      });
      changed = async function(files, filename) {
        var devnull, pipe, ref;
        if (files == null) {
          files = (await punk.p.add(task.entry)({}, task));
        }
        ref = task.pipes;
        // pass files through pipes
        for (devnull in ref) {
          pipe = ref[devnull];
          files = (await pipe(files, task));
        }
        // convert files
        if (task.to) {
          files = (await punk.p.to(task.to)(files, task));
        }
        // write files to FS
        files = (await punk.p.write(task)(files, task));
        if (filename) {
          // report
          return reporter.changed(filename);
        }
      };
    }
  };
};
