// Generated by CoffeeScript 2.1.1
var mm, uuid;

uuid = require('uuid/v1');

mm = require('micromatch');

module.exports = function(punk) {
  var getToRun, reporter, tasks;
  reporter = punk.reporter;
  punk._tasks = tasks = {};
  getToRun = function(ts) {
    var i, j, key, keys, len, len1, name, ret;
    ret = {};
    for (i = 0, len = ts.length; i < len; i++) {
      name = ts[i];
      if (typeof name === 'function') {
        ret[uuid()] = name;
        continue;
      } else if (typeof name === 'string') {
        keys = mm(Object.keys(tasks), [name]);
        for (j = 0, len1 = keys.length; j < len1; j++) {
          key = keys[j];
          ret[key] = tasks[key];
        }
        if (keys.length === 0) {
          reporter.tasksNotFound(ts);
        }
      }
    }
    return ret;
  };
  punk.task = punk.tasks = function(task) {
    return Object.assign(tasks, task);
  };
  punk.run = async function(ts) {
    var e, toRun;
    if (!Array.isArray(ts)) {
      ts = [ts];
    }
    toRun = getToRun(ts);
    try {
      return (await punk.d.eachAsync(toRun, async function(setting, name) {
        var cont;
        if (typeof setting === 'function') {
          cont = punk.collection([]);
          return (await (setting.call(cont)));
        } else {
          return (await punk._runTask(name, setting));
        }
      }));
    } catch (error) {
      e = error;
      return reporter.error(e);
    }
  };
  punk.startRun = async function() {
    reporter.start();
    reporter.usingConfig(punk.filename);
    punk.d.keepAlive();
    await punk.run(...arguments);
    if (!punk.alive) {
      return reporter.end();
    }
  };
  punk.startWatch = async function() {
    reporter.startWatch();
    reporter.usingConfig(punk.filename);
    punk.d.keepAlive();
    return (await punk.watch(...arguments));
  };
  punk.seq = punk.sequence = function() {
    var r, tsks;
    tsks = punk.d.flat(arguments);
    r = async function() {
      var i, len, results, task;
      results = [];
      for (i = 0, len = tsks.length; i < len; i++) {
        task = tsks[i];
        results.push((await punk.run(task)));
      }
      return results;
    };
    r[punk.s.isSequence] = true;
    return r;
  };
  return punk.e = punk.event = function(f) {
    var r;
    r = function() {
      return f();
    };
    r[punk.s.isEvent] = true;
    return r;
  };
};
