// Generated by CoffeeScript 2.1.1
module.exports = function(punk) {
  var s;
  s = {
    entry: {},
    default: Symbol('some default value'),
    isSequence: Symbol('some sequence of tasks'),
    isEvent: Symbol('event.')
  };
  s.entry.outFile = s.entry;
  return punk.s = punk.symbols = s;
};
