// Generated by CoffeeScript 2.1.1
module.exports = function(punk) {
  var s;
  s = {
    entry: {},
    default: Symbol('Some default value.'),
    isSequence: Symbol('Some sequence of tasks.'),
    isEvent: Symbol('Event.')
  };
  s.entry.outFile = s.entry;
  return punk.s = punk.symbols = s;
};
