// Generated by CoffeeScript 2.1.1
var resolve;

resolve = require('resolve');

module.exports = function(recess) {
  var reporter;
  reporter = recess.reporter;
  recess._use = function(plugin) {
    var name, pth, ref, ref1, value;
    if (plugin === void 0) {
      return;
    }
    if (!plugin) {
      reporter.pluginNotFound();
    }
    // get plugin from string
    if ((ref = typeof plugin) === 'string' || ref === 'number') {
      try {
        pth = resolve.sync(plugin, {
          basedir: recess.dirname
        });
      } catch (error) {}
      if (pth == null) {
        reporter.pluginNotFound(plugin);
      }
      plugin = require(pth);
    }
    if (typeof plugin === 'function') {
      plugin = plugin(recess, reporter);
    }
    // merge
    if (plugin.pipes) {
      ref1 = plugin.pipes;
      for (name in ref1) {
        value = ref1[name];
        if (recess.p[name]) {
          reporter.pluginsConflict(name);
        } else {
          recess.p[name] = value;
        }
      }
    }
    if (plugin.converters) {
      Object.assign(recess.converters, plugin.converters);
    }
    if (plugin.minifiers) {
      Object.assign(recess.minifiers, plugin.minifiers);
    }
    if (plugin.tasks) {
      return Object.assign(recess.fastTasks, plugin.tasks);
    }
  };
  return recess.use = function() {
    var name, plugin, plugins, results;
    if (arguments.length > 1) {
      plugins = arguments;
    } else if (Array.isArray(arguments[0])) {
      plugins = arguments[0];
    } else {
      plugins = [arguments[0]];
    }
    results = [];
    for (name in plugins) {
      plugin = plugins[name];
      results.push(recess._use(plugin));
    }
    return results;
  };
};
