// Generated by CoffeeScript 2.0.2
module.exports = function(punk) {
  var reporter;
  reporter = punk.reporter;
  punk._use = function(plugin) {
    var name, ref, value;
    if (typeof plugin === 'function') {
      plugin = plugin(punk, reporter);
    }
    if (plugin.pipes) {
      ref = plugin.pipes;
      for (name in ref) {
        value = ref[name];
        if (punk.p[name]) {
          reporter.pluginsConflict(name);
        } else {
          if (Array.isArray(value)) {
            value.textInput = true;
            punk.p[name] = value[0];
          } else {
            punk.p[name] = value;
          }
        }
      }
    }
    if (plugin.converters) {
      Object.assign(punk.converters, plugin.converters);
    }
    if (plugin.minifiers) {
      return Object.assign(punk.minifiers, plugin.minifiers);
    }
  };
  return punk.use = function() {
    var name, plugin, plugins, results;
    if (arguments.length > 1) {
      plugins = arguments;
    } else if (Array.isArray(arguments[0])) {
      plugins = arguments[0];
    } else {
      plugins = [arguments[0]];
    }
    results = [];
    for (name in plugins) {
      plugin = plugins[name];
      results.push(punk._use(plugin));
    }
    return results;
  };
};
