// Generated by CoffeeScript 2.0.2
var chokidar;

chokidar = require('chokidar');

module.exports = function(punk, reporter) {
  return {
    watch: async function(settings) {
      var e;
      reporter.start();
      reporter.usingConfig(punk.filename);
      try {
        await punk.d.mapAsync(settings, async function(setting, name) {
          return (await punk._runTask(name, setting));
        });
        return reporter.end();
      } catch (error) {
        e = error;
        return reporter.error(e);
      }
    }
  };
};
