// Generated by CoffeeScript 2.1.1
module.exports = function(recess) {
  var plugin, reporter;
  reporter = recess.reporter;
  plugin = {};
  plugin.pipes = {
    concat: function(settings, separator) {
      // set settings to standard form
      if ((separator != null) && typeof settings !== 'object') {
        settings = {
          output: settings,
          separator: separator
        };
      } else if (typeof settings !== 'object') {
        settings = {
          output: settings,
          separator: ''
        };
      } else {
        reporter.fatal(new Error('Settings not defined!'));
      }
      
      // PIPE #
      return recess.i.buffer(function(files) {
        var file, i, joinList, len, out, r;
        separator = Buffer.from(settings.separator);
        // buffer concat list
        joinList = [];
        for (i = 0, len = files.length; i < len; i++) {
          file = files[i];
          joinList.push(file.contents, separator);
        }
        joinList.pop();
        out = Buffer.concat(joinList);
        // new file storage
        r = [];
        r.push(new recess.File(settings.output, out));
        return r;
      });
    }
  };
  plugin.pipes.rename = plugin.pipes.concat;
  return plugin;
};
