// Generated by CoffeeScript 2.0.2
module.exports = function(punk, reporter) {
  var plugin;
  plugin = {};
  plugin.pipes = {
    concat: function(settings, separator) {
      // set settings to standard form
      if ((separator != null) && typeof settings !== 'object') {
        settings = {
          output: settings,
          separator: separator
        };
      } else if (typeof settings !== 'object') {
        settings = {
          output: settings,
          separator: ''
        };
      } else {
        reporter.error(new Error('Settings not defined!'));
      }
      
      // PIPE #
      return function(files) {
        var contents, joinList, name, out, r;
        separator = Buffer.from(settings.separator);
        // buffer concat list
        joinList = [];
        for (name in files) {
          contents = files[name];
          joinList.push(contents, separator);
        }
        joinList.pop();
        out = Buffer.concat(joinList);
        // new file storage
        r = {};
        r[settings.output] = out;
        return r;
      };
    }
  };
  plugin.pipes.rename = plugin.pipes.concat;
  return plugin;
};
