// Generated by CoffeeScript 2.0.2
module.exports = function(punk, reporter) {
  var plugin;
  plugin = {};
  plugin.pipes = {
    concat: function(settings) {
      // set settings to standard form
      if (typeof settings === 'string') {
        settings = {
          output: settings
        };
      }
      // PIPE #
      return function(files) {
        var arr, contents, name, r;
        // no filename
        if (settings.output == null) {
          throw new Error('"concat" needs output file name!');
        }
        // data collector
        arr = [];
        // add all files' contents to data collector
        for (name in files) {
          contents = files[name];
          arr.push(contents);
        }
        
        // new file storage
        r = {};
        // join contents of files
        r[settings.output] = arr.join(settings.separator || '');
        return r;
      };
    }
  };
  return plugin;
};
