// Generated by CoffeeScript 2.1.1
module.exports = function(recess) {
  var plugin, reporter;
  reporter = recess.reporter;
  plugin = {};
  plugin.pipes = {
    convert: function(settings, tr) {
      var ref;
      if ((ref = typeof settings) !== 'number' && ref !== 'string') {
        reporter.fatal('Setting must be a number or string!');
      }
      return recess.i.buffer(async function(files, cond) {
        var r;
        r = (await recess.d.mapAsync(files, async function(file) {
          var collection, ext, pipe;
          ext = recess.d.getType(file);
          // if there's needed converter
          if (recess.converters[ext] && recess.converters[ext][settings]) {
            pipe = recess.converters[ext][settings];
            collection = recess.collection([file], cond);
            await collection.pipe(pipe);
            file = collection.files[0];
            file.setExt(settings);
            // pipe file
            return file;
          } else if (ext === settings) {
            return file;
          } else if (tr) {

          } else {
            // remove file
            reporter.noConverter(file.path, settings);
            return file;
          }
        }));
        return r;
      });
    }
  };
  plugin.pipes.to = plugin.pipes.ex = plugin.pipes.convert;
  return plugin;
};
