// Generated by CoffeeScript 2.1.1
module.exports = function(recess) {
  var plugin, reporter;
  reporter = recess.reporter;
  plugin = {};
  plugin.pipes = {
    minify: function(settings) {
      return recess.i.buffer(async function(files, cond) {
        var r;
        r = (await recess.d.mapAsync(files, async function(file) {
          var collection, ext, pipe;
          ext = recess.d.getType(file);
          // if there's needed converter
          if (recess.minifiers[ext]) {
            // find converter
            pipe = recess.minifiers[ext];
            collection = recess.collection([file], cond);
            await collection.pipe(pipe);
            file = collection.files[0];
            // pipe file
            return file;
          } else {
            // remove file
            reporter.noMin(file.path);
          }
        }));
        return r;
      });
    }
  };
  plugin.pipes.min = plugin.pipes.minify;
  return plugin;
};
