// Generated by CoffeeScript 2.0.2
module.exports = function(punk) {
  var plugin, reporter;
  reporter = punk.reporter;
  plugin = {};
  plugin.pipes = {
    minify: function(settings) {
      return async function(files, cond) {
        var r;
        r = (await punk.d.mapAsync(files, async function(file) {
          var collection, ext, pipe;
          ext = punk.d.getType(file);
          // if there's needed converter
          if (punk.converters[ext] && punk.converters[ext][settings]) {
            // find converter
            pipe = punk.converters[ext];
            collection = new punk.Collection([file], cond);
            await collection.pipe(pipe);
            file = collection.files[0];
            // pipe file
            return file;
          } else {
            // remove file
            reporter.noMin(file.path);
          }
        }));
        return r;
      };
    }
  };
  plugin.pipes.min = plugin.pipes.minify;
  return plugin;
};
