// Generated by CoffeeScript 2.0.2
var bufferize, chalk, getExt, isBuffer, isSvg, path, type;

type = require('file-type');

path = require('path');

chalk = require('chalk');

isSvg = require('is-svg');

isBuffer = require('is-buffer');

bufferize = function(files) {
  var file, name, results;
  results = [];
  for (name in files) {
    file = files[name];
    if (!isBuffer(file)) {
      results.push(files[name] = Buffer.from(file));
    } else {
      results.push(void 0);
    }
  }
  return results;
};

getExt = function(name = '') {
  var ext;
  ext = path.extname(name).split('.');
  return ext[ext.length - 1];
};

module.exports = function(punk, reporter) {
  var plugin;
  plugin = {};
  plugin.pipes = {
    minify: function(settings) {
      return async function(files, cond) {
        var ext, f, file, name, pipe;
        for (name in files) {
          file = files[name];
          // get type of file
          ext = punk.d.getType(name, file);
          
          // if there's needed converter
          if (punk.minifiers[ext]) {
            pipe = punk.minifiers[ext];
            f = {};
            f[name] = file;
            // pipe file
            files[name] = Buffer.from(((await pipe(f, cond)))[name]);
          } else {
            // remove file
            delete files[name];
            reporter.noConverter(name, ext);
          }
        }
        return files;
      };
    }
  };
  // plugin.pipes.to = plugin.pipes.ex = plugin.pipes.convert
  return plugin;
};
