// Generated by CoffeeScript 2.0.2
module.exports = function() {
  var plugin;
  plugin = {};
  plugin.pipes = {
    mute: function(files) {
      if (files) {
        return [];
      } else {
        return function() {
          return [];
        };
      }
    }
  };
  return plugin;
};
