// Generated by CoffeeScript 2.0.2
module.exports = function() {
  var plugin;
  plugin = {};
  plugin.pipes = {
    mute: function() {
      return function() {
        return {};
      };
    }
  };
  return plugin;
};
