// Generated by CoffeeScript 2.1.1
var path, relative;

path = require('path');

relative = require('relative');

module.exports = function(punk) {
  var plugin, reporter;
  reporter = punk.reporter;
  plugin = {};
  plugin.pipes = {
    wrap: (settings) => {
      // PIPE #
      return punk.i.any(function(files, cond) {
        var file, i, len;
        for (i = 0, len = files.length; i < len; i++) {
          file = files[i];
          file.path = relative(cond.workdir, file.path);
          file.path = path.join(settings, file.path);
        }
        return files;
      });
    },
    unwrap: (settings = 1) => {
      // PIPE #
      return punk.i.any(function(files, cond) {
        var devnull, file, i, j, len, ref;
        for (i = 0, len = files.length; i < len; i++) {
          file = files[i];
          file.path = file.path.split(path.sep);
          for (devnull = j = 0, ref = settings; 0 <= ref ? j <= ref : j >= ref; devnull = 0 <= ref ? ++j : --j) {
            file.path.shift();
          }
          file.path = file.path.join('/');
        }
        return files;
      });
    }
  };
  return plugin;
};
