// Generated by CoffeeScript 2.1.1
var path, relative;

path = require('path');

relative = require('relative');

module.exports = function(recess) {
  var plugin, reporter;
  reporter = recess.reporter;
  plugin = {};
  plugin.pipes = {
    wrap: (settings) => {
      // PIPE #
      return recess.i.any(function(files, cond) {
        var file, i, len;
        for (i = 0, len = files.length; i < len; i++) {
          file = files[i];
          file.path = relative(cond.workdir, file.path);
          file.path = path.join(settings, file.path);
        }
        return files;
      });
    },
    unwrap: (reg, str = "") => {
      // PIPE #
      return recess.i.any(function(files, cond) {
        var file, i, len, xp;
        xp = new RegExp(reg + '/?');
        for (i = 0, len = files.length; i < len; i++) {
          file = files[i];
          file.path = file.path.replace(xp, str);
        }
        return files;
      });
    }
  };
  return plugin;
};
