// Generated by CoffeeScript 2.1.1
var fs, path;

path = require('path');

fs = require('fs-extra');

module.exports = function(punk) {
  var plugin, reporter;
  reporter = punk.reporter;
  plugin = {};
  plugin.pipes = {
    del: () => {
      return punk.i.any(function(files, cond) {
        var file, i, len, pth, results;
        results = [];
        for (i = 0, len = files.length; i < len; i++) {
          file = files[i];
          pth = path.resolve(cond.workdir, file.path);
          results.push(reporter.log(pth));
        }
        return results;
      });
    }
  };
  plugin.pipes.remove = plugin.pipes.del;
  return plugin;
};
