// Generated by CoffeeScript 2.1.1
var fs, path;

path = require('path');

fs = require('fs-extra');

module.exports = function(recess) {
  var plugin, reporter;
  reporter = recess.reporter;
  plugin = {};
  plugin.pipes = {
    del: function() {
      return recess.i.any(async function(files, cond) {
        await recess.d.eachAsync(files, async function(file) {
          var pth;
          pth = path.resolve(cond.workdir, file.path);
          return (await fs.remove(pth));
        });
        return files;
      });
    }
  };
  plugin.pipes.remove = plugin.pipes.del;
  return plugin;
};
