// Generated by CoffeeScript 2.0.2
module.exports = function(punk) {
  var plugin, reporter;
  reporter = punk.reporter;
  plugin = {};
  plugin.pipes = {
    header: function(settings) {
      return async function(files, cond) {
        var b;
        b = Buffer.from(settings);
        return (await punk.d.eachAsync(files, function(file) {
          return file.contents = Buffer.concat([b, file.contents]);
        }));
      };
    }
  };
  return plugin;
};
