// Generated by CoffeeScript 2.1.1
module.exports = function(punk) {
  var plugin, reporter;
  reporter = punk.reporter;
  plugin = {};
  plugin.pipes = {
    header: function(settings) {
      return punk.i.buffer(async function(files, cond) {
        var b;
        b = Buffer.from(settings);
        await punk.d.eachAsync(files, function(file) {
          return file.contents = Buffer.concat([b, file.contents]);
        });
        return files;
      });
    },
    footer: function(settings) {
      return punk.i.buffer(async function(files, cond) {
        var b;
        b = Buffer.from(settings);
        await punk.d.eachAsync(files, function(file) {
          return file.contents = Buffer.concat([file.contents, b]);
        });
        return files;
      });
    }
  };
  return plugin;
};
