// Generated by CoffeeScript 2.0.2
var fs, path;

path = require('path');

fs = require('fs-extra');

module.exports = function(punk, reporter) {
  var plugin;
  plugin = {};
  plugin.pipes = {
    write: function(setting) {
      // PIPE #
      return async function(files, cond) {
        var out, rg, to, workdir;
        workdir = setting.workdir || cond.workdir || './';
        if ((files.length === 1) && (setting.outFile != null)) {
          out = path.resolve(workdir, setting.outFile);
          to = punk.d.getExt(out);
          rg = punk.d.getType(files[0]);
          if (to !== rg) {
            files = (await punk.p.to(to)(files, cond));
          }
          // if there is a single file, write its contents to path, which specified in setting.outFile
          await fs.remove(out);
          await fs.writeFile(out, files[0].contents);
        } else if (files.length === 0) {

        } else if (setting.outDir || setting.outDirectory) {
          out = setting.outDir || setting.outDirectory;
          // if there are multiple files, write they to directory, which specified in setting.outDir
          await punk.d.eachAsync(files, async function(file) {
            var realPath;
            // absolute path
            realPath = path.resolve(workdir, out, file.path);
            await fs.remove(realPath);
            await fs.mkdirp(path.dirname(realPath));
            await fs.writeFile(realPath, file.contents);
          });
        }
        return files;
      };
    },
    outFile: function(setting) {
      return async function(files, cond) {
        return (await plugin.pipes.write({
          outFile: setting
        })(files, cond));
      };
    },
    outDir: function(setting) {
      return async function(files, cond) {
        return (await plugin.pipes.write({
          outDir: setting
        })(files, cond));
      };
    }
  };
  plugin.pipes.outDirectory = plugin.pipes.outDir;
  plugin.pipes.dest = plugin.pipes.write;
  return plugin;
};
